---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-generic-pv
  namespace: media-hosting
  labels:
    bucket: shared
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 8Ti
  nfs:
    server: 192.168.7.155
    path: /mnt/main/media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-generic-pvc
  namespace: media-hosting
spec:
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      bucket: shared
  resources:
    requests:
      storage: 8Ti