apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: xmpp
resources:
  - xmpp-cert.yaml
  - xmpp.yaml
  - xmppsvc.yaml
  - xmppingress.yaml
  - xmpp-configmap.yaml
  - tailscale.yaml