apiVersion: v1
kind: ConfigMap
metadata:
  name: xmpp-configmap
  namespace: xmpp
data:
  ejabberd.yaml: |
    hosts: 
      - xmpp.caffeinatedope.net
    certfiles:
      - /etc/ssl/tls-combined.pem
    modules:
      mod_roster:    {}
      mod_configure: {}
      mod_disco:     {}
      mod_private:   {}
      mod_time:      {}
      mod_last:      {}
      mod_version:   {}
      mod_adhoc: {}