---
apiVersion: v1
kind: Service
metadata:
  name: xmpp-service
  namespace: xmpp
spec:
  type: LoadBalancer
  selector:
    app: prosody
  ports:
  - port: 5222
    name: insecure
    targetPort: 5222
  - port: 5269
    name: s2s
    targetPort: 5269
  - port: 5280
    name: http
    targetPort: 5280
  - port: 5281
    name: https
    targetPort: 5281
