apiVersion: apps/v1
kind: Deployment
metadata:
  name: xmpp-deployment
  labels:
    app: xmpp
  namespace: xmpp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xmpp
  template:
    metadata:
      labels:
        app: xmpp
    spec:
      serviceAccountName: tailscale
      securityContext:
        runAsUser: 9000
        runAsGroup: 9000
        fsGroup: 9000
        fsGroupChangePolicy: "Always"
      containers:
      - name: xmpp
        image: ghcr.io/processone/ejabberd
        ports:
        - containerPort: 5222
        - containerPort: 5223
        - containerPort: 5269
        - containerPort: 5443
        env:
          - name: EJABBERD_MACRO_ADMIN
            value: caffeinatedope@xmpp.caffeinatedope.net
          - name: EJABBERD_MACRO_HOST
            value: xmpp.caffeinatedope.net
          - name: PROSODY_VIRTUAL_HOSTS
            value: xmpp.caffeinatedope.net
          - name: REGISTER_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: xmpp-userconfig
                key: pass
        volumeMounts:
        - name: config-volume
          readOnly: true
          mountPath: "/opt/ejabberd/conf/ejabberd.yml"
          subPath: "ejabberd.yaml"
        - name: cert-volume
          readOnly: true
          mountPath: "/etc/ssl/"
        - name: datastore 
          readOnly: false
          mountPath: "/opt/ejabberd/database"

      - name: ts-sidecar
        imagePullPolicy: Always
        image: "ghcr.io/tailscale/tailscale:latest"
        env:
        - name: TS_KUBE_SECRET
          value: "tailscale-auth"
        - name: TS_USERSPACE
          value: "false"
        - name: TS_DEBUG_FIREWALL_MODE
          value: auto
        - name: TS_HOSTNAME
          value: prosody
        - name: TS_AUTHKEY
          valueFrom:
            secretKeyRef:
              name: tailscale-auth
              key: TS_AUTHKEY
              optional: false
        - name: TS_EXTRA_ARGS
          value: "--login-server=https://headscale.caffeinatedope.net"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        securityContext:
          privileged: true
      volumes:
      - name: cert-volume
        secret:
          secretName: xmpp-cert
      - name: config-volume
        configMap:
          name: xmpp-configmap
      - name: datastore
        persistentVolumeClaim:
          claimName: xmpp-store