apiVersion: v1
kind: ConfigMap
metadata:
  name: xmpp-configmap
  namespace: xmpp
data:
  config.dist: |
    admins = { "caffeinatedope" }
    allow_registration = true -- Allow users to register new accounts
    motd_text = [[ Let's all love Lain ]]