---
apiVersion: v1
kind: Service
metadata:
  name: xmpp-service
  namespace: xmpp
spec:
  type: LoadBalancer
  selector:
    app: prosody
  ports:
  - port: 5222
    name: insecure
    targetPort: 5222
  ports:
  - port: 5222
    name: secure
    targetPort: 5222
