apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xmpp-store
  namespace: xmpp
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: truenas-nfs