apiVersion: apps/v1
kind: Deployment
metadata:
  name: prosody-deployment
  labels:
    app: prosody
  namespace: xmpp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prosody
  template:
    metadata:
      labels:
        app: prosody
    spec:
      serviceAccountName: tailscale
      containers:
      - name: prosody
        image: prosodyim/prosody:13.0
        ports:
        - containerPort: 5222
        env:
          - name: LOCAL
            value: caffeinatedope
          - name: DOMAIN
            value: xmpp.caffeinatedope.net
          - name: PROSODY_VIRTUAL_HOSTS
            value: xmpp.caffeinatedope.net
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: xmpp-userconfig
                key: pass
          - name: PROSODY_ENABLE_MODULES
            value: register,motd,welcome,watchregistrations,mam
        volumeMounts:
        - name: config-volume
          readOnly: true
          mountPath: "/etc/prosody/conf.d/custom.cfg.lua"
          subPath: "config.dist"
        - name: cert-volume
          readOnly: true
          mountPath: "/etc/prosody/certs/xmpp.caffeinatedope.net.crt"
          subPath: "tls.crt"
        - name: cert-volume
          readOnly: true
          mountPath: "/etc/prosody/certs/xmpp.caffeinatedope.net.key"
          subPath: "tls.key" 
      - name: ts-sidecar
        imagePullPolicy: Always
        image: "ghcr.io/tailscale/tailscale:latest"
        env:
        - name: TS_KUBE_SECRET
          value: "tailscale-auth"
        - name: TS_USERSPACE
          value: "false"
        - name: TS_DEBUG_FIREWALL_MODE
          value: auto
        - name: TS_HOSTNAME
          value: prosody
        - name: TS_AUTHKEY
          valueFrom:
            secretKeyRef:
              name: tailscale-auth
              key: TS_AUTHKEY
              optional: false
        - name: TS_EXTRA_ARGS
          value: "--login-server=https://headscale.caffeinatedope.net"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        securityContext:
          privileged: true
      volumes:
      - name: cert-volume
        secret:
          secretName: xmpp-cert
      - name: config-volume
        configMap:
          name: xmpp-configmap