apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: xmpp-cert
  namespace: xmpp
spec:
  # Secret names are always required.
  secretName: xmpp-cert
  issuerRef:
    name: cf-cluster-Issuer
    kind: ClusterIssuer
  dnsNames:
    - xmpp.caffeinatedope.net