apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-deployment
  namespace: blog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: blog
        image: codeberg.org/caffeinatedope/blog:latest@sha256:356e35b341c9f9315f76219c1d6e81081282ae4c40e8ee0ee2c8fd4db2e5d61c # {"$imagepolicy": "blog:blog-imagepolicy"}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4321
