tcp:
  routers:
    xmpp-router:
      entryPoints:
        - xmpp
      service: xmpp-service
      rule: "HostSNI(`*`)"
    xmpp-s2s-router:
      entryPoints:
        - xmpp-s2s
      service: xmpp-service
      rule: "HostSNI(`*`)"
    xmpp-router-http:
      entryPoints:
        - web
      service: xmpp-http
      rule: "HostSNI(`*`)"
    xmpp-router-https:
      entryPoints:
        - websecure
      service: xmpp-https
      rule: "HostSNI(`*`)"

  services:
    xmpp-service:
      loadBalancer:
        servers:
        - address: "xmpp.cf.service:5222"
    xmpp-s2s:
      loadBalancer:
        servers:
        - address: "xmpp.cf.service:5269"
    xmpp-http:
      loadBalancer:
        servers:
        - address: "xmpp.cf.service:5280"
    xmpp-https:
      loadBalancer:
        servers:
        - address: "xmpp.cf.service:5281"