tcp:
  routers:
    xmpp-router:
      entryPoints:
        - xmpp
      service: xmpp-service
      rule: "HostSNI(`*`)"
    xmpp-router-secure:
      entryPoints:
        - xmppsecure
      service: xmpp-service-secure
      rule: "HostSNI(`*`)"

  services:
    xmpp-service:
      loadBalancer:
        servers:
        - address: "prosody.cf.service:5222"
    xmpp-service-secure:
      loadBalancer:
        servers:
        - address: "prosody.cf.service:5223"