kind: ConfigMap
apiVersion: v1
metadata:
  name: ricochet-configmap
  namespace: ricochet
data:
  config.toml: |
    [paths]
    creator = 'https://caffeinatedope.net/'
    github = 'https://github.com/CaffeinatedOpe/ricochet'
    [behaviors]
    default_page = "https://github.com/CaffeinatedOpe/ricochet"
