apiVersion: apps/v1
kind: Deployment
metadata:
  name: ricochet-deployment
  namespace: ricochet
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ricochet
  template:
    metadata:
      labels:
        app: ricochet
    spec:
      containers:
      - name: ricochet
        image: ghcr.io/caffeinatedope/ricochet-dev:latest@sha256:903114b13e4bc70421d658c882e89bfb4200c5cf57433ca0e00a42a4760a306f # {"$imagepolicy": "ricochet:ricochet-imagepolicy"}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
        env:
        - CONFIGMAP 1
        - CUSTOM_DEFAULT "https://caffeinatedope.net"
        volumeMounts:
        - name: config-volume
          mountPath: /config
      volumes:
      - name: config-volume
        configMap:
          name: ricochet-configmap
