apiVersion: apps/v1
kind: Deployment
metadata:
  name: ricochet-deployment
  namespace: ricochet
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ricochet
  template:
    metadata:
      labels:
        app: ricochet
    spec:
      containers:
      - name: ricochet
        image: ghcr.io/caffeinatedope/ricochet-dev:latest@sha256:dfdfb5612891b50c81d936cb0de3bf480eba8001d2bfb5de0470cf40d7d08b96 # {"$imagepolicy": "ricochet:ricochet-imagepolicy"}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
        volumeMounts:
        - name: config-volume
          mountPath: /config
      volumes:
      - name: config-volume
        configMap:
          name: ricochet-configmap
