---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ricochet-deployment
  namespace: ricochet
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ricochet
  template:
    metadata:
      labels:
        app: ricochet
    spec:
      containers:
      - name: ricochet
        image: ghcr.io/caffeinatedope/ricochet-dev:latest@sha256:a6757a3c3296fc9415ac743e6fa258efa97fd74b70445a639a2fc41f72a1c664  # {"$imagepolicy": "ricochet:ricochet-imagepolicy"}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
        volumeMounts:
        - name: config-volume
          mountPath: /config
      volumes:
      - name: config-volume
        configMap:
          name: ricochet-configmap