apiVersion: v1
kind: Namespace
metadata:
  name: blog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-deployment
  namespace: blog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: blog
        image: ghcr.io/caffeinatedope/blog:latest@sha256:61c43e84b04c3928f40037b637f020810950fef69513e27ed60edc37c3e4c96f # {"$imagepolicy": "blog:blog-imagepolicy"}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4321
