apiVersion: v1
kind: Namespace
metadata:
  name: blog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-deployment
  namespace: blog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: blog
        image: ghcr.io/caffeinatedope/blog:latest@sha256:6dfa800501f4c000d6a839b6c481a28f8fbde5afb72eb01195a0d3f932bfc60c # {"$imagepolicy": "blog:blog-imagepolicy"}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4321
