apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ricochet
resources:
  - ricochet-cert.yaml
  - ricochet.yaml
  - ricochetsvc.yaml
  - ricochetingress.yaml
  - ricochet-imagerepo.yaml
  - ricochet-configmap.yaml