apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: httpbin-ingress
  namespace: httpbin
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`httpbin.caffeinatedope.net`)
    kind: Rule
    services:
    - name: httpbin-service
      port: 80
  tls: 
    secretName: wildcard-cert