---
apiVersion: v1
kind: Namespace
metadata:
  name: gpus
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gpu-management
  namespace: gpus
spec:
  interval: 5m
  path: ./cluster/management/gpus
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: flux-system